version: '3.15'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=vasya
      - POSTGRES_PASSWORD=qwerty123
